export const MERMAID_RECOVERY_RN_TIMEOUT_MS = 42_000;
export const MERMAID_RECOVERY_BRIDGE_TIMEOUT_MS = 44_000;

export const WRAP_UP_ASSESSMENT_RN_TIMEOUT_MS = 310_000;
export const WRAP_UP_ASSESSMENT_BRIDGE_TIMEOUT_MS = 315_000;

export const TEACHING_PLAN_RN_TIMEOUT_MS = 200_000;
export const TEACHING_PLAN_BRIDGE_TIMEOUT_MS = 205_000;

export const COMPREHENSIVE_ANALYSIS_RN_TIMEOUT_MS = 200_000;
export const COMPREHENSIVE_ANALYSIS_BRIDGE_TIMEOUT_MS = 205_000;
