export interface RoleAwareHistoryLimits {
  maxEntries: number;
  userEntryChars: number;
  senseiEntryChars: number;
  totalChars: number;
}

export const MAIN_SENSEI_USER_MESSAGE_MAX_CHARS = 8000;
export const SELECTION_SENSEI_USER_MESSAGE_MAX_CHARS = 8000;

export const MAIN_SENSEI_HISTORY_ENTRY_MAX_CHARS = 200000;
export const SELECTION_SENSEI_RESPONSE_ENTRY_MAX_CHARS = 200000;

export const MAIN_SENSEI_HISTORY_MAX_ENTRIES = 40;
export const SELECTION_SENSEI_TRANSCRIPT_MAX_ENTRIES = 20;

export const MAIN_SENSEI_STRUCTURED_PROMPT_MAX_CHARS = 950000;
export const SELECTION_SENSEI_STRUCTURED_MODAL_MAX_CHARS = 800000;
export const SENSEI_ENHANCEMENT_ORIGINAL_MARKDOWN_MAX_CHARS = 250000;
export const SENSEI_ENHANCEMENT_STRUCTURED_INPUT_MAX_CHARS = 260000;

export const MAIN_SENSEI_HISTORY_LIMITS: RoleAwareHistoryLimits = {
  maxEntries: MAIN_SENSEI_HISTORY_MAX_ENTRIES,
  userEntryChars: MAIN_SENSEI_USER_MESSAGE_MAX_CHARS,
  senseiEntryChars: MAIN_SENSEI_HISTORY_ENTRY_MAX_CHARS,
  totalChars: MAIN_SENSEI_STRUCTURED_PROMPT_MAX_CHARS
};

export const SELECTION_SENSEI_MODAL_TRANSCRIPT_LIMITS: RoleAwareHistoryLimits = {
  maxEntries: SELECTION_SENSEI_TRANSCRIPT_MAX_ENTRIES,
  userEntryChars: SELECTION_SENSEI_USER_MESSAGE_MAX_CHARS,
  senseiEntryChars: SELECTION_SENSEI_RESPONSE_ENTRY_MAX_CHARS,
  totalChars: SELECTION_SENSEI_STRUCTURED_MODAL_MAX_CHARS
};
